version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/restart_apache.sh
      timeout: 60
      runas: root
